import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import "@fortawesome/fontawesome-svg-core/styles.css"; 
import { config } from "@fortawesome/fontawesome-svg-core";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faChevronDown, faMagnifyingGlass } from "@fortawesome/free-solid-svg-icons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

config.autoAddCss = false; 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${openSans.variable}`}>
      <body>
        <header>
          <nav>
            <Link href="/">
              <div className="header-logo">
                <img src="/logo.jpg"/>
                <h1>unbounce</h1>
              </div>
            </Link>
            <div className="link">
              <Link href="/product">Product</Link>
              <FontAwesomeIcon icon={faChevronDown} className="header-icon" />
            </div>
            <div className="link">
              <Link href="/solution">Solution</Link>
              <FontAwesomeIcon icon={faChevronDown} className="header-icon" />
            </div>
            <Link href="/pricing">Pricing</Link>
            <div className="link">
              <Link href="/learn">Learn</Link>
              <FontAwesomeIcon icon={faChevronDown} className="header-icon" />
            </div>
            <Link href="/contact">Contact</Link>
          </nav>
          <div className="user">
            <FontAwesomeIcon icon={faMagnifyingGlass} className="icon" />
            <Link href="/login" className="user-btn" id="login">Log in</Link>
            <Link href="/register" className="user-btn" id="start">Start My Free Trial</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
